# Generated by Django 2.1.4 on 2019-03-03 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20190113_0742'),
    ]

    operations = [
        migrations.CreateModel(
            name='s_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.CharField(max_length=11, unique=True)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('dob', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('mobile_number', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=10)),
                ('pin_code', models.CharField(max_length=7)),
                ('state', models.CharField(max_length=15)),
                ('language', models.CharField(max_length=50)),
                ('other_l', models.CharField(max_length=11, unique=True)),
                ('degree', models.CharField(max_length=10)),
            ],
        ),
    ]
